import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header/mainHeader";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Crave House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
